# Generated by Django 4.2.13 on 2024-06-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='convert_file',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='convert_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='user_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
